### ISSUE TITLE
ClusterRoleBinding requires Namespace

### ISSUE THREAD

**Issue by remissio** [mvisonneau/helm-charts#50]
https://github.com/mvisonneau/helm-charts/blob/3c50eb36c030336b7a7b68afb4d87203d91fd1e6/charts/gitlab-ci-pipelines-exporter/templates/serviceaccount.yaml#L21-L23

I'd like to suggest to insert the current Namespace:

```yaml
subjects:
- kind: ServiceAccount
  name: {{ template "exporter.serviceAccountName" . }}
  namespace: {{ .Release.namespace }}
```

Kubernetes expects a namespace to be referenced within the ClusterRoleBinding resource. Currently when trying to apply this chart setting "rbac.enabled = true" helm fails.
